### ISSUE TITLE
Suggestion: Database creation (IF NOT EXISTS) on init.

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [SourceMod-Store/store-webpanel#16]
Given I just had my friend go on an epic quest that lasted the entirety of the holy crusade, just to find the Table creation SQL files for the store_ tables, I feel that it is only fair that this package should autocheck the database on init to see if these tables exist. If not, don't complain about them, FUCKING CREATE THEM.

No but seriously, you should include the CREATE IF NOT EXISTS shit in post init if you do not already include them in an auto-install file.

**Comment by Arrow768** [comment]
So you are suggesting that the webpanel runs a CREATE IF NOT EXISTS Query for every table on every page load ?

**Comment by HDG-MrDeeJay** [comment]
Perhaps not on every page load for every page in the panel. Perhaps 
after login. After a "Successful" login (IE login details match), during 
the database tests, if there isn't something, run "CREATE IF NOT EXISTS 
`blah`"

**Comment by Arrow768** [comment]
I dont see the point of adding this, because this problem is prevented by following the installation tutorial of the store plugin:
https://github.com/alongubkin/store/wiki/Installing-Store#setting-up-the-database

AFTER the creation of the tables, the webpanel gets installed.
Its using the same database, so there should be no errors if someone follows the installation guide.

One day I might create a installer that installs the webpanel and the store plugin on the server.

**Comment by HDG-MrDeeJay** [comment]
The problem was that even though we followed the guidelines, we still 
were missing half of the database files.

**Comment by Arrow768** [comment]
The import of the db will be covered by the installer
