### ISSUE TITLE
.json import doesnt work

### ISSUE THREAD

**Issue by sword134** [SourceMod-Store/store-webpanel#55]
Since you closed it last time with just telling me to read the faq then im going to open it again since i read the faq about error 1054 and it didnt work.

I get this when trying to import a .json file:

https://gyazo.com/811ed9374bc8411e131af56d1d1dba67

It worked fine before i reinstalled the webpanel

**Comment by Arrow768** [comment]
Since you are unable to read the F.A.Q. : 
- If you use the latest version of the webpanel you have to use the latest version of the store plugin and the latest version of the database.
- Update your stuff and it will work.

**Comment by sword134** [comment]
You must be really stupid. I allready fucking did what the faq stated. STOP CLOSING THE TICKETS. If you are incapable of helping people then atleast dont fucking close the ticket?!

**Comment by Arrow768** [comment]
I will just repeat what I said:
- The problem is caused because you are using a outdated database.
- Update the database (any maybe the store plugin) and it will work.

This ticket has been closed because the problem you are describing is well known and a solution has been documented.

A few facts:
- Updating the database / store plugin is the accepted solution (multiple people reported this to be working) -> If it is not working for you, you are doing something wrong.
- A issue can be reopened if there is actually a problem. But I do not see a problem here.
- Opening multiple issues for the same problem will not make me more inclined to help you ( Related to #54 )
- Insulting me will not make me more inclined to help you.
- A step by step tutorial to solve this problem can be found on the forum by searching for the error (Which you obviously did not do)

How to proceed:
- Update the database and maybe the store plugin.
- If it does not work, post the names all the sql scripts that you have executed.
